//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoosterSysteem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int ID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string linkedFaculty { get; set; }
        public Nullable<double> availableHours { get; set; }
        public string availableDays { get; set; }
        public Nullable<double> availableWeeklyHours { get; set; }
        public string qualifiedCourse { get; set; }
        public string email { get; set; }
        public string note { get; set; }
    }
}
